import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-center items-center h-full">
        <h1 className="text-2xl font-black text-skin">Alireza Mashayekhi</h1>
        <p>ReactJs FrontEnd Developer</p>
      </div>
    </>
  );
}
